name: lintall
description: Enable as many lint rules as possible.
version: 0.1.0
repository: https://github.com/treeinfra/lintall
environment: {sdk: ^3.4.3}
topics:
  - lint
  - lint-rules
  - lint-rules-strict
  - strict
  - spider

dependencies:
  flutter_lints: ^4.0.0

dev_dependencies:
  test: ^1.24.0
